// -*- C++ -*-
#ifndef LSTEff_H
#define LSTEff_H
#include "Math/LorentzVector.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > LorentzVector;

class LSTEff {
private:
protected:
  unsigned int index;
  std::vector<float> *sim_pt_;
  TBranch *sim_pt_branch;
  bool sim_pt_isLoaded;
  std::vector<float> *sim_eta_;
  TBranch *sim_eta_branch;
  bool sim_eta_isLoaded;
  std::vector<float> *sim_phi_;
  TBranch *sim_phi_branch;
  bool sim_phi_isLoaded;
  std::vector<float> *sim_pca_dxy_;
  TBranch *sim_pca_dxy_branch;
  bool sim_pca_dxy_isLoaded;
  std::vector<float> *sim_pca_dz_;
  TBranch *sim_pca_dz_branch;
  bool sim_pca_dz_isLoaded;
  std::vector<int> *sim_q_;
  TBranch *sim_q_branch;
  bool sim_q_isLoaded;
  std::vector<int> *sim_pdgId_;
  TBranch *sim_pdgId_branch;
  bool sim_pdgId_isLoaded;
  std::vector<float> *sim_vx_;
  TBranch *sim_vx_branch;
  bool sim_vx_isLoaded;
  std::vector<float> *sim_vy_;
  TBranch *sim_vy_branch;
  bool sim_vy_isLoaded;
  std::vector<float> *sim_vz_;
  TBranch *sim_vz_branch;
  bool sim_vz_isLoaded;
  std::vector<float> *sim_vtxperp_;
  TBranch *sim_vtxperp_branch;
  bool sim_vtxperp_isLoaded;
  std::vector<float> *sim_trkNtupIdx_;
  TBranch *sim_trkNtupIdx_branch;
  bool sim_trkNtupIdx_isLoaded;
  std::vector<int> *sim_tcIdx_;
  TBranch *sim_tcIdx_branch;
  bool sim_tcIdx_isLoaded;
  std::vector<std::vector<int> > *sim_tcIdxAll_;
  TBranch *sim_tcIdxAll_branch;
  bool sim_tcIdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_tcIdxAllFrac_;
  TBranch *sim_tcIdxAllFrac_branch;
  bool sim_tcIdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_mdIdxAll_;
  TBranch *sim_mdIdxAll_branch;
  bool sim_mdIdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_mdIdxAllFrac_;
  TBranch *sim_mdIdxAllFrac_branch;
  bool sim_mdIdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_lsIdxAll_;
  TBranch *sim_lsIdxAll_branch;
  bool sim_lsIdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_lsIdxAllFrac_;
  TBranch *sim_lsIdxAllFrac_branch;
  bool sim_lsIdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_t3IdxAll_;
  TBranch *sim_t3IdxAll_branch;
  bool sim_t3IdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_t3IdxAllFrac_;
  TBranch *sim_t3IdxAllFrac_branch;
  bool sim_t3IdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_t5IdxAll_;
  TBranch *sim_t5IdxAll_branch;
  bool sim_t5IdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_t5IdxAllFrac_;
  TBranch *sim_t5IdxAllFrac_branch;
  bool sim_t5IdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_plsIdxAll_;
  TBranch *sim_plsIdxAll_branch;
  bool sim_plsIdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_plsIdxAllFrac_;
  TBranch *sim_plsIdxAllFrac_branch;
  bool sim_plsIdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_pt3IdxAll_;
  TBranch *sim_pt3IdxAll_branch;
  bool sim_pt3IdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_pt3IdxAllFrac_;
  TBranch *sim_pt3IdxAllFrac_branch;
  bool sim_pt3IdxAllFrac_isLoaded;
  std::vector<std::vector<int> > *sim_pt5IdxAll_;
  TBranch *sim_pt5IdxAll_branch;
  bool sim_pt5IdxAll_isLoaded;
  std::vector<std::vector<float> > *sim_pt5IdxAllFrac_;
  TBranch *sim_pt5IdxAllFrac_branch;
  bool sim_pt5IdxAllFrac_isLoaded;
  std::vector<std::vector<float> > *sim_simHitX_;
  TBranch *sim_simHitX_branch;
  bool sim_simHitX_isLoaded;
  std::vector<std::vector<float> > *sim_simHitY_;
  TBranch *sim_simHitY_branch;
  bool sim_simHitY_isLoaded;
  std::vector<std::vector<float> > *sim_simHitZ_;
  TBranch *sim_simHitZ_branch;
  bool sim_simHitZ_isLoaded;
  std::vector<std::vector<int> > *sim_simHitDetId_;
  TBranch *sim_simHitDetId_branch;
  bool sim_simHitDetId_isLoaded;
  std::vector<std::vector<int> > *sim_simHitLayer_;
  TBranch *sim_simHitLayer_branch;
  bool sim_simHitLayer_isLoaded;
  std::vector<std::vector<float> > *sim_simHitDistxyHelix_;
  TBranch *sim_simHitDistxyHelix_branch;
  bool sim_simHitDistxyHelix_isLoaded;
  std::vector<std::vector<float> > *sim_simHitLayerMinDistxyHelix_;
  TBranch *sim_simHitLayerMinDistxyHelix_branch;
  bool sim_simHitLayerMinDistxyHelix_isLoaded;
  std::vector<std::vector<float> > *sim_recoHitX_;
  TBranch *sim_recoHitX_branch;
  bool sim_recoHitX_isLoaded;
  std::vector<std::vector<float> > *sim_recoHitY_;
  TBranch *sim_recoHitY_branch;
  bool sim_recoHitY_isLoaded;
  std::vector<std::vector<float> > *sim_recoHitZ_;
  TBranch *sim_recoHitZ_branch;
  bool sim_recoHitZ_isLoaded;
  std::vector<std::vector<int> > *sim_recoHitDetId_;
  TBranch *sim_recoHitDetId_branch;
  bool sim_recoHitDetId_isLoaded;
  std::vector<float> *tc_pt_;
  TBranch *tc_pt_branch;
  bool tc_pt_isLoaded;
  std::vector<float> *tc_eta_;
  TBranch *tc_eta_branch;
  bool tc_eta_isLoaded;
  std::vector<float> *tc_phi_;
  TBranch *tc_phi_branch;
  bool tc_phi_isLoaded;
  std::vector<int> *tc_type_;
  TBranch *tc_type_branch;
  bool tc_type_isLoaded;
  std::vector<int> *tc_pt5Idx_;
  TBranch *tc_pt5Idx_branch;
  bool tc_pt5Idx_isLoaded;
  std::vector<int> *tc_pt3Idx_;
  TBranch *tc_pt3Idx_branch;
  bool tc_pt3Idx_isLoaded;
  std::vector<int> *tc_t5Idx_;
  TBranch *tc_t5Idx_branch;
  bool tc_t5Idx_isLoaded;
  std::vector<int> *tc_plsIdx_;
  TBranch *tc_plsIdx_branch;
  bool tc_plsIdx_isLoaded;
  std::vector<int> *tc_isFake_;
  TBranch *tc_isFake_branch;
  bool tc_isFake_isLoaded;
  std::vector<int> *tc_isDuplicate_;
  TBranch *tc_isDuplicate_branch;
  bool tc_isDuplicate_isLoaded;
  std::vector<int> *tc_simIdx_;
  TBranch *tc_simIdx_branch;
  bool tc_simIdx_isLoaded;
  std::vector<std::vector<int> > *tc_simIdxAll_;
  TBranch *tc_simIdxAll_branch;
  bool tc_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *tc_simIdxAllFrac_;
  TBranch *tc_simIdxAllFrac_branch;
  bool tc_simIdxAllFrac_isLoaded;
  std::vector<float> *md_pt_;
  TBranch *md_pt_branch;
  bool md_pt_isLoaded;
  std::vector<float> *md_eta_;
  TBranch *md_eta_branch;
  bool md_eta_isLoaded;
  std::vector<float> *md_phi_;
  TBranch *md_phi_branch;
  bool md_phi_isLoaded;
#ifdef CUT_VALUE_DEBUG
  std::vector<float> *md_dphi_;
  TBranch *md_dphi_branch;
  bool md_dphi_isLoaded;
  std::vector<float> *md_dphichange_;
  TBranch *md_dphichange_branch;
  bool md_dphichange_isLoaded;
  std::vector<float> *md_dz_;
  TBranch *md_dz_branch;
  bool md_dz_isLoaded;
#endif
  std::vector<float> *md_anchor_x_;
  TBranch *md_anchor_x_branch;
  bool md_anchor_x_isLoaded;
  std::vector<float> *md_anchor_y_;
  TBranch *md_anchor_y_branch;
  bool md_anchor_y_isLoaded;
  std::vector<float> *md_anchor_z_;
  TBranch *md_anchor_z_branch;
  bool md_anchor_z_isLoaded;
  std::vector<float> *md_other_x_;
  TBranch *md_other_x_branch;
  bool md_other_x_isLoaded;
  std::vector<float> *md_other_y_;
  TBranch *md_other_y_branch;
  bool md_other_y_isLoaded;
  std::vector<float> *md_other_z_;
  TBranch *md_other_z_branch;
  bool md_other_z_isLoaded;
  std::vector<int> *md_type_;
  TBranch *md_type_branch;
  bool md_type_isLoaded;
  std::vector<int> *md_layer_;
  TBranch *md_layer_branch;
  bool md_layer_isLoaded;
  std::vector<int> *md_detId_;
  TBranch *md_detId_branch;
  bool md_detId_isLoaded;
  std::vector<int> *md_isFake_;
  TBranch *md_isFake_branch;
  bool md_isFake_isLoaded;
  std::vector<int> *md_simIdx_;
  TBranch *md_simIdx_branch;
  bool md_simIdx_isLoaded;
  std::vector<std::vector<int> > *md_simIdxAll_;
  TBranch *md_simIdxAll_branch;
  bool md_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *md_simIdxAllFrac_;
  TBranch *md_simIdxAllFrac_branch;
  bool md_simIdxAllFrac_isLoaded;
  std::vector<float> *ls_pt_;
  TBranch *ls_pt_branch;
  bool ls_pt_isLoaded;
  std::vector<float> *ls_eta_;
  TBranch *ls_eta_branch;
  bool ls_eta_isLoaded;
  std::vector<float> *ls_phi_;
  TBranch *ls_phi_branch;
  bool ls_phi_isLoaded;
  std::vector<int> *ls_mdIdx0_;
  TBranch *ls_mdIdx0_branch;
  bool ls_mdIdx0_isLoaded;
  std::vector<int> *ls_mdIdx1_;
  TBranch *ls_mdIdx1_branch;
  bool ls_mdIdx1_isLoaded;
  std::vector<int> *ls_isFake_;
  TBranch *ls_isFake_branch;
  bool ls_isFake_isLoaded;
  std::vector<int> *ls_simIdx_;
  TBranch *ls_simIdx_branch;
  bool ls_simIdx_isLoaded;
#ifdef CUT_VALUE_DEBUG
  std::vector<int> *ls_zLos_;
  TBranch *ls_zLos_branch;
  bool ls_zLos_isLoaded;
  std::vector<int> *ls_zHis_;
  TBranch *ls_zHis_branch;
  bool ls_zHis_isLoaded;
  std::vector<int> *ls_rtLos_;
  TBranch *ls_rtLos_branch;
  bool ls_rtLos_isLoaded;
  std::vector<int> *ls_rtHis_;
  TBranch *ls_rtHis_branch;
  bool ls_rtHis_isLoaded;
  std::vector<int> *ls_dPhis_;
  TBranch *ls_dPhis_branch;
  bool ls_dPhis_isLoaded;
  std::vector<int> *ls_dPhiMins_;
  TBranch *ls_dPhiMins_branch;
  bool ls_dPhiMins_isLoaded;
  std::vector<int> *ls_dPhiMaxs_;
  TBranch *ls_dPhiMaxs_branch;
  bool ls_dPhiMaxs_isLoaded;
  std::vector<int> *ls_dPhiChanges_;
  TBranch *ls_dPhiChanges_branch;
  bool ls_dPhiChanges_isLoaded;
  std::vector<int> *ls_dPhiChangeMins_;
  TBranch *ls_dPhiChangeMins_branch;
  bool ls_dPhiChangeMins_isLoaded;
  std::vector<int> *ls_dPhiChangeMaxs_;
  TBranch *ls_dPhiChangeMaxs_branch;
  bool ls_dPhiChangeMaxs_isLoaded;
  std::vector<int> *ls_dAlphaInners_;
  TBranch *ls_dAlphaInners_branch;
  bool ls_dAlphaInners_isLoaded;
  std::vector<int> *ls_dAlphaOuters_;
  TBranch *ls_dAlphaOuters_branch;
  bool ls_dAlphaOuters_isLoaded;
  std::vector<int> *ls_dAlphaInnerOuters_;
  TBranch *ls_dAlphaInnerOuters_branch;
  bool ls_dAlphaInnerOuters_isLoaded;
#endif
  std::vector<std::vector<int> > *ls_simIdxAll_;
  TBranch *ls_simIdxAll_branch;
  bool ls_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *ls_simIdxAllFrac_;
  TBranch *ls_simIdxAllFrac_branch;
  bool ls_simIdxAllFrac_isLoaded;
  std::vector<float> *t3_pt_;
  TBranch *t3_pt_branch;
  bool t3_pt_isLoaded;
  std::vector<float> *t3_eta_;
  TBranch *t3_eta_branch;
  bool t3_eta_isLoaded;
  std::vector<float> *t3_phi_;
  TBranch *t3_phi_branch;
  bool t3_phi_isLoaded;
  std::vector<int> *t3_lsIdx0_;
  TBranch *t3_lsIdx0_branch;
  bool t3_lsIdx0_isLoaded;
  std::vector<int> *t3_lsIdx1_;
  TBranch *t3_lsIdx1_branch;
  bool t3_lsIdx1_isLoaded;
  std::vector<int> *t3_isFake_;
  TBranch *t3_isFake_branch;
  bool t3_isFake_isLoaded;
  std::vector<int> *t3_isDuplicate_;
  TBranch *t3_isDuplicate_branch;
  bool t3_isDuplicate_isLoaded;
  std::vector<int> *t3_simIdx_;
  TBranch *t3_simIdx_branch;
  bool t3_simIdx_isLoaded;
  std::vector<std::vector<int> > *t3_simIdxAll_;
  TBranch *t3_simIdxAll_branch;
  bool t3_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *t3_simIdxAllFrac_;
  TBranch *t3_simIdxAllFrac_branch;
  bool t3_simIdxAllFrac_isLoaded;
  std::vector<float> *t5_pt_;
  TBranch *t5_pt_branch;
  bool t5_pt_isLoaded;
  std::vector<float> *t5_eta_;
  TBranch *t5_eta_branch;
  bool t5_eta_isLoaded;
  std::vector<float> *t5_phi_;
  TBranch *t5_phi_branch;
  bool t5_phi_isLoaded;
  std::vector<int> *t5_t3Idx0_;
  TBranch *t5_t3Idx0_branch;
  bool t5_t3Idx0_isLoaded;
  std::vector<int> *t5_t3Idx1_;
  TBranch *t5_t3Idx1_branch;
  bool t5_t3Idx1_isLoaded;
  std::vector<int> *t5_isFake_;
  TBranch *t5_isFake_branch;
  bool t5_isFake_isLoaded;
  std::vector<int> *t5_isDuplicate_;
  TBranch *t5_isDuplicate_branch;
  bool t5_isDuplicate_isLoaded;
  std::vector<int> *t5_simIdx_;
  TBranch *t5_simIdx_branch;
  bool t5_simIdx_isLoaded;
  std::vector<std::vector<int> > *t5_simIdxAll_;
  TBranch *t5_simIdxAll_branch;
  bool t5_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *t5_simIdxAllFrac_;
  TBranch *t5_simIdxAllFrac_branch;
  bool t5_simIdxAllFrac_isLoaded;
  std::vector<float> *pls_pt_;
  TBranch *pls_pt_branch;
  bool pls_pt_isLoaded;
  std::vector<float> *pls_eta_;
  TBranch *pls_eta_branch;
  bool pls_eta_isLoaded;
  std::vector<float> *pls_phi_;
  TBranch *pls_phi_branch;
  bool pls_phi_isLoaded;
  std::vector<int> *pls_nhit_;
  TBranch *pls_nhit_branch;
  bool pls_nhit_isLoaded;
  std::vector<float> *pls_hit0_x_;
  TBranch *pls_hit0_x_branch;
  bool pls_hit0_x_isLoaded;
  std::vector<float> *pls_hit0_y_;
  TBranch *pls_hit0_y_branch;
  bool pls_hit0_y_isLoaded;
  std::vector<float> *pls_hit0_z_;
  TBranch *pls_hit0_z_branch;
  bool pls_hit0_z_isLoaded;
  std::vector<float> *pls_hit1_x_;
  TBranch *pls_hit1_x_branch;
  bool pls_hit1_x_isLoaded;
  std::vector<float> *pls_hit1_y_;
  TBranch *pls_hit1_y_branch;
  bool pls_hit1_y_isLoaded;
  std::vector<float> *pls_hit1_z_;
  TBranch *pls_hit1_z_branch;
  bool pls_hit1_z_isLoaded;
  std::vector<float> *pls_hit2_x_;
  TBranch *pls_hit2_x_branch;
  bool pls_hit2_x_isLoaded;
  std::vector<float> *pls_hit2_y_;
  TBranch *pls_hit2_y_branch;
  bool pls_hit2_y_isLoaded;
  std::vector<float> *pls_hit2_z_;
  TBranch *pls_hit2_z_branch;
  bool pls_hit2_z_isLoaded;
  std::vector<float> *pls_hit3_x_;
  TBranch *pls_hit3_x_branch;
  bool pls_hit3_x_isLoaded;
  std::vector<float> *pls_hit3_y_;
  TBranch *pls_hit3_y_branch;
  bool pls_hit3_y_isLoaded;
  std::vector<float> *pls_hit3_z_;
  TBranch *pls_hit3_z_branch;
  bool pls_hit3_z_isLoaded;
  std::vector<int> *pls_isFake_;
  TBranch *pls_isFake_branch;
  bool pls_isFake_isLoaded;
  std::vector<int> *pls_isDuplicate_;
  TBranch *pls_isDuplicate_branch;
  bool pls_isDuplicate_isLoaded;
  std::vector<int> *pls_simIdx_;
  TBranch *pls_simIdx_branch;
  bool pls_simIdx_isLoaded;
  std::vector<std::vector<int> > *pls_simIdxAll_;
  TBranch *pls_simIdxAll_branch;
  bool pls_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *pls_simIdxAllFrac_;
  TBranch *pls_simIdxAllFrac_branch;
  bool pls_simIdxAllFrac_isLoaded;
  std::vector<float> *pt3_pt_;
  TBranch *pt3_pt_branch;
  bool pt3_pt_isLoaded;
  std::vector<float> *pt3_eta_;
  TBranch *pt3_eta_branch;
  bool pt3_eta_isLoaded;
  std::vector<float> *pt3_phi_;
  TBranch *pt3_phi_branch;
  bool pt3_phi_isLoaded;
  std::vector<int> *pt3_plsIdx_;
  TBranch *pt3_plsIdx_branch;
  bool pt3_plsIdx_isLoaded;
  std::vector<int> *pt3_t3Idx_;
  TBranch *pt3_t3Idx_branch;
  bool pt3_t3Idx_isLoaded;
  std::vector<int> *pt3_isFake_;
  TBranch *pt3_isFake_branch;
  bool pt3_isFake_isLoaded;
  std::vector<int> *pt3_isDuplicate_;
  TBranch *pt3_isDuplicate_branch;
  bool pt3_isDuplicate_isLoaded;
  std::vector<int> *pt3_simIdx_;
  TBranch *pt3_simIdx_branch;
  bool pt3_simIdx_isLoaded;
  std::vector<std::vector<int> > *pt3_simIdxAll_;
  TBranch *pt3_simIdxAll_branch;
  bool pt3_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *pt3_simIdxAllFrac_;
  TBranch *pt3_simIdxAllFrac_branch;
  bool pt3_simIdxAllFrac_isLoaded;
  std::vector<float> *pt5_pt_;
  TBranch *pt5_pt_branch;
  bool pt5_pt_isLoaded;
  std::vector<float> *pt5_eta_;
  TBranch *pt5_eta_branch;
  bool pt5_eta_isLoaded;
  std::vector<float> *pt5_phi_;
  TBranch *pt5_phi_branch;
  bool pt5_phi_isLoaded;
  std::vector<int> *pt5_plsIdx_;
  TBranch *pt5_plsIdx_branch;
  bool pt5_plsIdx_isLoaded;
  std::vector<int> *pt5_t5Idx_;
  TBranch *pt5_t5Idx_branch;
  bool pt5_t5Idx_isLoaded;
  std::vector<int> *pt5_isFake_;
  TBranch *pt5_isFake_branch;
  bool pt5_isFake_isLoaded;
  std::vector<int> *pt5_isDuplicate_;
  TBranch *pt5_isDuplicate_branch;
  bool pt5_isDuplicate_isLoaded;
  std::vector<int> *pt5_simIdx_;
  TBranch *pt5_simIdx_branch;
  bool pt5_simIdx_isLoaded;
  std::vector<std::vector<int> > *pt5_simIdxAll_;
  TBranch *pt5_simIdxAll_branch;
  bool pt5_simIdxAll_isLoaded;
  std::vector<std::vector<float> > *pt5_simIdxAllFrac_;
  TBranch *pt5_simIdxAllFrac_branch;
  bool pt5_simIdxAllFrac_isLoaded;

public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const std::vector<float> &sim_pt();
  const std::vector<float> &sim_eta();
  const std::vector<float> &sim_phi();
  const std::vector<float> &sim_pca_dxy();
  const std::vector<float> &sim_pca_dz();
  const std::vector<int> &sim_q();
  const std::vector<int> &sim_pdgId();
  const std::vector<float> &sim_vx();
  const std::vector<float> &sim_vy();
  const std::vector<float> &sim_vz();
  const std::vector<float> &sim_vtxperp();
  const std::vector<float> &sim_trkNtupIdx();
  const std::vector<int> &sim_tcIdx();
  const std::vector<std::vector<int> > &sim_tcIdxAll();
  const std::vector<std::vector<float> > &sim_tcIdxAllFrac();
  const std::vector<std::vector<int> > &sim_mdIdxAll();
  const std::vector<std::vector<float> > &sim_mdIdxAllFrac();
  const std::vector<std::vector<int> > &sim_lsIdxAll();
  const std::vector<std::vector<float> > &sim_lsIdxAllFrac();
  const std::vector<std::vector<int> > &sim_t3IdxAll();
  const std::vector<std::vector<float> > &sim_t3IdxAllFrac();
  const std::vector<std::vector<int> > &sim_t5IdxAll();
  const std::vector<std::vector<float> > &sim_t5IdxAllFrac();
  const std::vector<std::vector<int> > &sim_plsIdxAll();
  const std::vector<std::vector<float> > &sim_plsIdxAllFrac();
  const std::vector<std::vector<int> > &sim_pt3IdxAll();
  const std::vector<std::vector<float> > &sim_pt3IdxAllFrac();
  const std::vector<std::vector<int> > &sim_pt5IdxAll();
  const std::vector<std::vector<float> > &sim_pt5IdxAllFrac();
  const std::vector<std::vector<float> > &sim_simHitX();
  const std::vector<std::vector<float> > &sim_simHitY();
  const std::vector<std::vector<float> > &sim_simHitZ();
  const std::vector<std::vector<int> > &sim_simHitDetId();
  const std::vector<std::vector<int> > &sim_simHitLayer();
  const std::vector<std::vector<float> > &sim_simHitDistxyHelix();
  const std::vector<std::vector<float> > &sim_simHitLayerMinDistxyHelix();
  const std::vector<std::vector<float> > &sim_recoHitX();
  const std::vector<std::vector<float> > &sim_recoHitY();
  const std::vector<std::vector<float> > &sim_recoHitZ();
  const std::vector<std::vector<int> > &sim_recoHitDetId();
  const std::vector<float> &tc_pt();
  const std::vector<float> &tc_eta();
  const std::vector<float> &tc_phi();
  const std::vector<int> &tc_type();
  const std::vector<int> &tc_pt5Idx();
  const std::vector<int> &tc_pt3Idx();
  const std::vector<int> &tc_t5Idx();
  const std::vector<int> &tc_plsIdx();
  const std::vector<int> &tc_isFake();
  const std::vector<int> &tc_isDuplicate();
  const std::vector<int> &tc_simIdx();
  const std::vector<std::vector<int> > &tc_simIdxAll();
  const std::vector<std::vector<float> > &tc_simIdxAllFrac();
  const std::vector<float> &md_pt();
  const std::vector<float> &md_eta();
  const std::vector<float> &md_phi();
#ifdef CUT_VALUE_DEBUG
  const std::vector<float> &md_dphi();
  const std::vector<float> &md_dphichange();
  const std::vector<float> &md_dz();
#endif
  const std::vector<float> &md_anchor_x();
  const std::vector<float> &md_anchor_y();
  const std::vector<float> &md_anchor_z();
  const std::vector<float> &md_other_x();
  const std::vector<float> &md_other_y();
  const std::vector<float> &md_other_z();
  const std::vector<int> &md_type();
  const std::vector<int> &md_layer();
  const std::vector<int> &md_detId();
  const std::vector<int> &md_isFake();
  const std::vector<int> &md_simIdx();
  const std::vector<std::vector<int> > &md_simIdxAll();
  const std::vector<std::vector<float> > &md_simIdxAllFrac();
  const std::vector<float> &ls_pt();
  const std::vector<float> &ls_eta();
  const std::vector<float> &ls_phi();
  const std::vector<int> &ls_mdIdx0();
  const std::vector<int> &ls_mdIdx1();
  const std::vector<int> &ls_isFake();
  const std::vector<int> &ls_simIdx();
#ifdef CUT_VALUE_DEBUG
  const std::vector<int> &ls_zLos();
  const std::vector<int> &ls_zHis();
  const std::vector<int> &ls_rtLos();
  const std::vector<int> &ls_rtHis();
  const std::vector<int> &ls_dPhis();
  const std::vector<int> &ls_dPhiMins();
  const std::vector<int> &ls_dPhiMaxs();
  const std::vector<int> &ls_dPhiChanges();
  const std::vector<int> &ls_dPhiChangeMins();
  const std::vector<int> &ls_dPhiChangeMaxs();
  const std::vector<int> &ls_dAlphaInners();
  const std::vector<int> &ls_dAlphaOuters();
  const std::vector<int> &ls_dAlphaInnerOuters();
#endif
  const std::vector<std::vector<int> > &ls_simIdxAll();
  const std::vector<std::vector<float> > &ls_simIdxAllFrac();
  const std::vector<float> &t3_pt();
  const std::vector<float> &t3_eta();
  const std::vector<float> &t3_phi();
  const std::vector<int> &t3_lsIdx0();
  const std::vector<int> &t3_lsIdx1();
  const std::vector<int> &t3_isFake();
  const std::vector<int> &t3_isDuplicate();
  const std::vector<int> &t3_simIdx();
  const std::vector<std::vector<int> > &t3_simIdxAll();
  const std::vector<std::vector<float> > &t3_simIdxAllFrac();
  const std::vector<float> &t5_pt();
  const std::vector<float> &t5_eta();
  const std::vector<float> &t5_phi();
  const std::vector<int> &t5_t3Idx0();
  const std::vector<int> &t5_t3Idx1();
  const std::vector<int> &t5_isFake();
  const std::vector<int> &t5_isDuplicate();
  const std::vector<int> &t5_simIdx();
  const std::vector<std::vector<int> > &t5_simIdxAll();
  const std::vector<std::vector<float> > &t5_simIdxAllFrac();
  const std::vector<float> &pls_pt();
  const std::vector<float> &pls_eta();
  const std::vector<float> &pls_phi();
  const std::vector<int> &pls_nhit();
  const std::vector<float> &pls_hit0_x();
  const std::vector<float> &pls_hit0_y();
  const std::vector<float> &pls_hit0_z();
  const std::vector<float> &pls_hit1_x();
  const std::vector<float> &pls_hit1_y();
  const std::vector<float> &pls_hit1_z();
  const std::vector<float> &pls_hit2_x();
  const std::vector<float> &pls_hit2_y();
  const std::vector<float> &pls_hit2_z();
  const std::vector<float> &pls_hit3_x();
  const std::vector<float> &pls_hit3_y();
  const std::vector<float> &pls_hit3_z();
  const std::vector<int> &pls_isFake();
  const std::vector<int> &pls_isDuplicate();
  const std::vector<int> &pls_simIdx();
  const std::vector<std::vector<int> > &pls_simIdxAll();
  const std::vector<std::vector<float> > &pls_simIdxAllFrac();
  const std::vector<float> &pt3_pt();
  const std::vector<float> &pt3_eta();
  const std::vector<float> &pt3_phi();
  const std::vector<int> &pt3_plsIdx();
  const std::vector<int> &pt3_t3Idx();
  const std::vector<int> &pt3_isFake();
  const std::vector<int> &pt3_isDuplicate();
  const std::vector<int> &pt3_simIdx();
  const std::vector<std::vector<int> > &pt3_simIdxAll();
  const std::vector<std::vector<float> > &pt3_simIdxAllFrac();
  const std::vector<float> &pt5_pt();
  const std::vector<float> &pt5_eta();
  const std::vector<float> &pt5_phi();
  const std::vector<int> &pt5_plsIdx();
  const std::vector<int> &pt5_t5Idx();
  const std::vector<int> &pt5_isFake();
  const std::vector<int> &pt5_isDuplicate();
  const std::vector<int> &pt5_simIdx();
  const std::vector<std::vector<int> > &pt5_simIdxAll();
  const std::vector<std::vector<float> > &pt5_simIdxAllFrac();
  static void progress(int nEventsTotal, int nEventsChain);
};

#ifndef __CINT__
extern LSTEff lstEff;
#endif

namespace tas {

  const std::vector<float> &sim_pt();
  const std::vector<float> &sim_eta();
  const std::vector<float> &sim_phi();
  const std::vector<float> &sim_pca_dxy();
  const std::vector<float> &sim_pca_dz();
  const std::vector<int> &sim_q();
  const std::vector<int> &sim_pdgId();
  const std::vector<float> &sim_vx();
  const std::vector<float> &sim_vy();
  const std::vector<float> &sim_vz();
  const std::vector<float> &sim_vtxperp();
  const std::vector<float> &sim_trkNtupIdx();
  const std::vector<int> &sim_tcIdx();
  const std::vector<std::vector<int> > &sim_tcIdxAll();
  const std::vector<std::vector<float> > &sim_tcIdxAllFrac();
  const std::vector<std::vector<int> > &sim_mdIdxAll();
  const std::vector<std::vector<float> > &sim_mdIdxAllFrac();
  const std::vector<std::vector<int> > &sim_lsIdxAll();
  const std::vector<std::vector<float> > &sim_lsIdxAllFrac();
  const std::vector<std::vector<int> > &sim_t3IdxAll();
  const std::vector<std::vector<float> > &sim_t3IdxAllFrac();
  const std::vector<std::vector<int> > &sim_t5IdxAll();
  const std::vector<std::vector<float> > &sim_t5IdxAllFrac();
  const std::vector<std::vector<int> > &sim_plsIdxAll();
  const std::vector<std::vector<float> > &sim_plsIdxAllFrac();
  const std::vector<std::vector<int> > &sim_pt3IdxAll();
  const std::vector<std::vector<float> > &sim_pt3IdxAllFrac();
  const std::vector<std::vector<int> > &sim_pt5IdxAll();
  const std::vector<std::vector<float> > &sim_pt5IdxAllFrac();
  const std::vector<std::vector<float> > &sim_simHitX();
  const std::vector<std::vector<float> > &sim_simHitY();
  const std::vector<std::vector<float> > &sim_simHitZ();
  const std::vector<std::vector<int> > &sim_simHitDetId();
  const std::vector<std::vector<int> > &sim_simHitLayer();
  const std::vector<std::vector<float> > &sim_simHitDistxyHelix();
  const std::vector<std::vector<float> > &sim_simHitLayerMinDistxyHelix();
  const std::vector<std::vector<float> > &sim_recoHitX();
  const std::vector<std::vector<float> > &sim_recoHitY();
  const std::vector<std::vector<float> > &sim_recoHitZ();
  const std::vector<std::vector<int> > &sim_recoHitDetId();
  const std::vector<float> &tc_pt();
  const std::vector<float> &tc_eta();
  const std::vector<float> &tc_phi();
  const std::vector<int> &tc_type();
  const std::vector<int> &tc_pt5Idx();
  const std::vector<int> &tc_pt3Idx();
  const std::vector<int> &tc_t5Idx();
  const std::vector<int> &tc_plsIdx();
  const std::vector<int> &tc_isFake();
  const std::vector<int> &tc_isDuplicate();
  const std::vector<int> &tc_simIdx();
  const std::vector<std::vector<int> > &tc_simIdxAll();
  const std::vector<std::vector<float> > &tc_simIdxAllFrac();
  const std::vector<float> &md_pt();
  const std::vector<float> &md_eta();
  const std::vector<float> &md_phi();
#ifdef CUT_VALUE_DEBUG
  const std::vector<float> &md_pt();
  const std::vector<float> &md_eta();
  const std::vector<float> &md_phi();
#endif
  const std::vector<float> &md_anchor_x();
  const std::vector<float> &md_anchor_y();
  const std::vector<float> &md_anchor_z();
  const std::vector<float> &md_other_x();
  const std::vector<float> &md_other_y();
  const std::vector<float> &md_other_z();
  const std::vector<int> &md_type();
  const std::vector<int> &md_layer();
  const std::vector<int> &md_detId();
  const std::vector<int> &md_isFake();
  const std::vector<int> &md_simIdx();
  const std::vector<std::vector<int> > &md_simIdxAll();
  const std::vector<std::vector<float> > &md_simIdxAllFrac();
  const std::vector<float> &ls_pt();
  const std::vector<float> &ls_eta();
  const std::vector<float> &ls_phi();
  const std::vector<int> &ls_mdIdx0();
  const std::vector<int> &ls_mdIdx1();
  const std::vector<int> &ls_isFake();
  const std::vector<int> &ls_simIdx();
#ifdef CUT_VALUE_DEBUG
  const std::vector<int> &ls_zLos();
  const std::vector<int> &ls_zHis();
  const std::vector<int> &ls_rtLos();
  const std::vector<int> &ls_rtHis();
  const std::vector<int> &ls_dPhis();
  const std::vector<int> &ls_dPhiMins();
  const std::vector<int> &ls_dPhiMaxs();
  const std::vector<int> &ls_dPhiChanges();
  const std::vector<int> &ls_dPhiChangeMins();
  const std::vector<int> &ls_dPhiChangeMaxs();
  const std::vector<int> &ls_dAlphaInners();
  const std::vector<int> &ls_dAlphaOuters();
  const std::vector<int> &ls_dAlphaInnerOuters();
#endif
  const std::vector<std::vector<int> > &ls_simIdxAll();
  const std::vector<std::vector<float> > &ls_simIdxAllFrac();
  const std::vector<float> &t3_pt();
  const std::vector<float> &t3_eta();
  const std::vector<float> &t3_phi();
  const std::vector<int> &t3_lsIdx0();
  const std::vector<int> &t3_lsIdx1();
  const std::vector<int> &t3_isFake();
  const std::vector<int> &t3_isDuplicate();
  const std::vector<int> &t3_simIdx();
  const std::vector<std::vector<int> > &t3_simIdxAll();
  const std::vector<std::vector<float> > &t3_simIdxAllFrac();
  const std::vector<float> &t5_pt();
  const std::vector<float> &t5_eta();
  const std::vector<float> &t5_phi();
  const std::vector<int> &t5_t3Idx0();
  const std::vector<int> &t5_t3Idx1();
  const std::vector<int> &t5_isFake();
  const std::vector<int> &t5_isDuplicate();
  const std::vector<int> &t5_simIdx();
  const std::vector<std::vector<int> > &t5_simIdxAll();
  const std::vector<std::vector<float> > &t5_simIdxAllFrac();
  const std::vector<float> &pls_pt();
  const std::vector<float> &pls_eta();
  const std::vector<float> &pls_phi();
  const std::vector<int> &pls_nhit();
  const std::vector<float> &pls_hit0_x();
  const std::vector<float> &pls_hit0_y();
  const std::vector<float> &pls_hit0_z();
  const std::vector<float> &pls_hit1_x();
  const std::vector<float> &pls_hit1_y();
  const std::vector<float> &pls_hit1_z();
  const std::vector<float> &pls_hit2_x();
  const std::vector<float> &pls_hit2_y();
  const std::vector<float> &pls_hit2_z();
  const std::vector<float> &pls_hit3_x();
  const std::vector<float> &pls_hit3_y();
  const std::vector<float> &pls_hit3_z();
  const std::vector<int> &pls_isFake();
  const std::vector<int> &pls_isDuplicate();
  const std::vector<int> &pls_simIdx();
  const std::vector<std::vector<int> > &pls_simIdxAll();
  const std::vector<std::vector<float> > &pls_simIdxAllFrac();
  const std::vector<float> &pt3_pt();
  const std::vector<float> &pt3_eta();
  const std::vector<float> &pt3_phi();
  const std::vector<int> &pt3_plsIdx();
  const std::vector<int> &pt3_t3Idx();
  const std::vector<int> &pt3_isFake();
  const std::vector<int> &pt3_isDuplicate();
  const std::vector<int> &pt3_simIdx();
  const std::vector<std::vector<int> > &pt3_simIdxAll();
  const std::vector<std::vector<float> > &pt3_simIdxAllFrac();
  const std::vector<float> &pt5_pt();
  const std::vector<float> &pt5_eta();
  const std::vector<float> &pt5_phi();
  const std::vector<int> &pt5_plsIdx();
  const std::vector<int> &pt5_t5Idx();
  const std::vector<int> &pt5_isFake();
  const std::vector<int> &pt5_isDuplicate();
  const std::vector<int> &pt5_simIdx();
  const std::vector<std::vector<int> > &pt5_simIdxAll();
  const std::vector<std::vector<float> > &pt5_simIdxAllFrac();
}  // namespace tas
#endif
